# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='title')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(help_text='The end time must be later than the start time.', verbose_name='end')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('event_type', models.CharField(choices=[('salon', 'salon'), ('manifestation', 'manifestation'), ('dedicace', 'dedicace'), ('radio/mumble', 'radio/mumble'), ('emission TV', 'emission TV'), ('conference', 'conference')], max_length=20)),
                ('event_subject', models.CharField(choices=[('geopolitic', 'g\xe9opolitique'), ('politic', 'politique'), ('economy', '\xe9conomie'), ('ecology', '\xe9cologie'), ('alternative', 'alternative'), ('media', 'm\xe9dia'), ('history', 'histoire'), ('spirituality', 'spiritualit\xe9'), ('culture', 'cultures'), ('science', 'sciences')], max_length=20)),
                ('website', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('reg_price', models.CharField(blank=True, default='', max_length=300)),
                ('reg_type', models.CharField(blank=True, default='', max_length=100)),
                ('reg_email', models.CharField(blank=True, default='', max_length=50)),
                ('reg_website', models.URLField(blank=True, default='')),
                ('reg_facebook', models.URLField(blank=True, default='')),
                ('poster', models.FileField(blank=True, upload_to='uploads/')),
                ('landscape', models.FileField(blank=True, upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=50)),
                ('building', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='event.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, to='event.Organizer'),
        ),
    ]
