# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Location', verbose_name='location'),
        ),
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='area',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
