# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160807_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organizer',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
