# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20160824_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('salon', 'Salon'), ('manifestation', 'Manifestation'), ('dedicace', 'D\xe9dicace'), ('mumble', 'Mumble'), ('emission TV', '\xc9mission TV'), ('conference', 'Conf\xe9rence'), ('theatre', 'Th\xe9atre'), ('cinema', 'Cin\xe9ma'), ('emission-radio', '\xc9mission radio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
