# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20160911_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
